version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build: 
    commands:
      - echo Installing npm dependencies
      - npm install
  test:
    commands:
      - echo Start testing
      - npm run test
  build:
    commands:
      - echo Build start on 'date'
      - npm run build

artifacts:
  files: 
    - "**/*"
  discard:path: no
  base-directory: dist
