export const questions = [
	// JavaScript Questions
	{
		id: 1,
		category: "JavaScript",
		question: "What is the correct way to declare a variable in JavaScript?",
		options: {
			A: "var myVar;",
			B: "variable myVar;",
			C: "let myVar;",
			D: "const myVar;",
		},
		correctAnswer: "A",
		isAnswered: false,
	},
	{
		id: 2,
		category: "JavaScript",
		question: "Which method is used to parse a JSON string?",
		options: {
			A: "JSON.parse()",
			B: "JSON.stringify()",
			C: "JSON.decode()",
			D: "JSON.convert()",
		},
		correctAnswer: "A",
		isAnswered: false,
	},
	{
		id: 3,
		category: "JavaScript",
		question: "What will `console.log(typeof NaN)` output?",
		options: { A: '"number"', B: '"NaN"', C: '"undefined"', D: '"object"' },
		correctAnswer: "A",
		isAnswered: false,
	},
	{
		id: 4,
		category: "JavaScript",
		question:
			"Which of the following is NOT a primitive data type in JavaScript?",
		options: { A: "String", B: "Number", C: "Object", D: "Boolean" },
		correctAnswer: "C",
		isAnswered: false,
	},
	{
		id: 5,
		category: "JavaScript",
		question: "What does the `push()` method do?",
		options: {
			A: "Adds an element to the beginning of an array",
			B: "Adds an element to the end of an array",
			C: "Removes the last element of an array",
			D: "Removes the first element of an array",
		},
		correctAnswer: "B",
		isAnswered: false,
	},
	{
		id: 6,
		category: "JavaScript",
		question: "Which keyword is used to define an asynchronous function?",
		options: { A: "async", B: "await", C: "promise", D: "defer" },
		correctAnswer: "A",
		isAnswered: false,
	},
	{
		id: 7,
		category: "JavaScript",
		question: 'What will the following code return: `Boolean("")`?',
		options: { A: "true", B: "false", C: "undefined", D: "null" },
		correctAnswer: "B",
		isAnswered: false,
	},
	{
		id: 8,
		category: "JavaScript",
		question: "Which operator is used to compare both value and type?",
		options: { A: "==", B: "===", C: "!=", D: "!==" },
		correctAnswer: "B",
		isAnswered: false,
	},
	{
		id: 9,
		category: "JavaScript",
		question: "What does the `map()` function do?",
		options: {
			A: "Transforms each element in an array",
			B: "Filters elements in an array",
			C: "Finds an element in an array",
			D: "Sorts an array",
		},
		correctAnswer: "A",
		isAnswered: false,
	},
	{
		id: 10,
		category: "JavaScript",
		question: "Which of the following statements is true about `null`?",
		options: {
			A: "It is an object",
			B: "It is a primitive data type",
			C: "It represents an intentional absence of any value",
			D: "All of the above",
		},
		correctAnswer: "D",
		isAnswered: false,
	},
	{
		id: 11,
		category: "JavaScript",
		question: "What is the output of `typeof []`?",
		options: { A: "array", B: "object", C: "undefined", D: "list" },
		correctAnswer: "B",
		isAnswered: false,
	},

	// React Questions
	{
		id: 12,
		category: "React",
		question: "What is the default export of a React component?",
		options: { A: "Component", B: "React", C: "render", D: "default" },
		correctAnswer: "A",
		isAnswered: false,
	},
	{
		id: 13,
		category: "React",
		question: "Which hook is used to manage state in functional components?",
		options: {
			A: "useState",
			B: "useEffect",
			C: "useReducer",
			D: "useContext",
		},
		correctAnswer: "A",
		isAnswered: false,
	},
	{
		id: 14,
		category: "React",
		question: "What is the purpose of `useEffect`?",
		options: {
			A: "To manage component state",
			B: "To perform side effects in function components",
			C: "To memoize values",
			D: "To create context",
		},
		correctAnswer: "B",
		isAnswered: false,
	},
	{
		id: 15,
		category: "React",
		question: "What does the `key` prop do in React?",
		options: {
			A: "Identifies which items have changed",
			B: "Sets a unique identifier for each component",
			C: "Controls component re-renders",
			D: "All of the above",
		},
		correctAnswer: "A",
		isAnswered: false,
	},
	{
		id: 16,
		category: "React",
		question: "How do you create a functional component in React?",
		options: {
			A: "function MyComponent() {}",
			B: "const MyComponent = () => {}",
			C: "Both A and B",
			D: "class MyComponent extends Component {}",
		},
		correctAnswer: "C",
		isAnswered: false,
	},
	{
		id: 17,
		category: "React",
		question: "What is the purpose of `React.Fragment`?",
		options: {
			A: "To return multiple elements without a parent node",
			B: "To define a component",
			C: "To manage state",
			D: "To create context",
		},
		correctAnswer: "A",
		isAnswered: false,
	},
	{
		id: 18,
		category: "React",
		question:
			"Which lifecycle method is called when a component is first rendered?",
		options: {
			A: "componentDidMount",
			B: "render",
			C: "componentDidUpdate",
			D: "constructor",
		},
		correctAnswer: "A",
		isAnswered: false,
	},
	{
		id: 19,
		category: "React",
		question: "What does `useContext` hook do?",
		options: {
			A: "Manages local component state",
			B: "Accesses context API",
			C: "Handles side effects",
			D: "Memoizes values",
		},
		correctAnswer: "B",
		isAnswered: false,
	},
	{
		id: 20,
		category: "React",
		question: "What is a controlled component?",
		options: {
			A: "A component that doesn't hold its own state",
			B: "A component that uses hooks",
			C: "A component that handles its own state",
			D: "A component that renders a list",
		},
		correctAnswer: "A",
		isAnswered: false,
	},
	{
		id: 21,
		category: "React",
		question: "Which method is used to update the state in a class component?",
		options: {
			A: "setState",
			B: "updateState",
			C: "changeState",
			D: "modifyState",
		},
		correctAnswer: "A",
		isAnswered: false,
	},
];
